### ISSUE TITLE
Cannot force unwrap value of non-optional type 'URL'

### ISSUE THREAD

**Issue by ykws** [el-hoshino/ViDRep-Sample#3]
Build failed でエラーになります。

https://github.com/el-hoshino/ViDRep-Sample/blob/0844dd00ec0ae7477ff7ae98a7980eaa7541d214/Shared/Source/Infrastructures/CataasAPIClient.swift#L13

```swift
    private let baseURL: URL = URL.init(string: "https://cataas.com")!
```

or 

```swift
    private let baseURL: URL = URL(string: "https://cataas.com")!
```

これで回避できるのですが、よくわかっていないです 🤔

**Comment by el-hoshino** [comment]
@ykws Xcode 12.5でもこれ発生していますか？（自分のところでは発生していないので… 🤔

**Comment by ykws** [comment]
@el-hoshino なるほどです。 Xcode 12.5 では確かに発生しないですね。
12.4 だと発生しています。

違いは、 Xcode 12.5 = Swift 5.4, Xcode 12.4 = Swift 5.3 で、

https://developer.apple.com/support/xcode/ > Minimum requirements and supported SDKs

5.4 からの ⬇️ これによる影響ですね

[Extend implicit member syntax to cover chains of member reference](https://github.com/apple/swift-evolution/blob/main/proposals/0287-implicit-member-chains.md)

**Comment by ykws** [comment]
#4 Xcode のバージョンが明記してあっても良いと思ったので PR 作成しました。

**Comment by el-hoshino** [comment]
@ykws ありがとうございます！マージしましたー
